let colors = ["red", "yellow", "blue", "orange", "pink", "white"];
console.log(colors.splice(4));
console.log(colors);
console.log(colors.splice(0,1));
console.log(colors);
console.log(colors.splice(0,1, "black", "gray"));
console.log(colors);
console.log(colors.splice(0,0, "pink", "sky"));
console.log(colors);
console.log(colors.splice(1,0, "maroon"));
console.log(colors);
